version: '3'
services:
  app:
    image: maissene/nestjs-movies-api:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_DB_URI: mongodb://mongo:27017/movie-favorites
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
